services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - ./config:/mosquitto/config
    networks:
      - leoiot

  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=leogreen
      - DOCKER_INFLUXDB_INIT_ORG=leoiot
      - DOCKER_INFLUXDB_INIT_BUCKET=server_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=ih3lGQ2dVqXG7ec0Ai-flUi5ZWTqp3AChtwI0fu4014-cn5h0MRE6-RcWtlL1yYGUaaSg6NOtcW_TEjQdGGA5A==
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - leoiot

  telegraf:
    image: telegraf:latest
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - mosquitto
      - influxdb
    networks:
      - leoiot

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    networks:
      - leoiot

  quarkus-app:
    build:
      context: ./backend/sinus-generator
      dockerfile: src/main/docker/Dockerfile
    environment:
      - MQTT_HOST=mosquitto
    depends_on:
      - mosquitto
    networks:
      - leoiot

networks:
  leoiot:
    driver: bridge

volumes:
  mosquitto_data:
  influxdb_data: